apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-cloud-env
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- if .Values.global.secrets.aws.enable }}
  CLOUD_NAME: AWS
  AWS_QUEUE_URL: {{ .Values.global.secrets.aws.AWS_QUEUE_URL }}
  AWS_QUEUE_ARN: {{ .Values.global.secrets.aws.AWS_QUEUE_ARN }}
  {{- if not .Values.global.secrets.aws.use_iam_role }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.secrets.aws.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.secrets.aws.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: {{ .Values.global.secrets.aws.AWS_DEFAULT_REGION }}
  {{- end }}
  {{- else if .Values.global.secrets.minio.enable }}
  CLOUD_NAME: MINIO
  AWS_ACCESS_KEY_ID: {{ .Values.global.secrets.minio.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.secrets.minio.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: {{ .Values.global.secrets.minio.AWS_DEFAULT_REGION }}
  MINIO_ENDPOINT: {{ .Values.global.secrets.minio.MINIO_ENDPOINT }}
  MINIO_QUEUE_ARN: {{ .Values.global.secrets.minio.MINIO_QUEUE_ARN }}
  {{- else if .Values.global.secrets.gcs.enable }}
  CLOUD_NAME: GCP
  GCP_DEFAULT_REGION: {{ .Values.global.secrets.gcs.GCP_DEFAULT_REGION }}
  GCP_DEFAULT_ZONE: {{ .Values.global.secrets.gcs.GCP_DEFAULT_ZONE }}
  AWS_ACCESS_KEY_ID: gcpminio
  AWS_SECRET_ACCESS_KEY: gcpminio
  {{- else if .Values.global.secrets.azure.enable }}
  CLOUD_NAME: AZURE
  STORAGE_ACCOUNT_ACCESS_KEY: {{ .Values.global.secrets.azure.STORAGE_ACCOUNT_ACCESS_KEY }}
  STORAGE_ACCOUNT_NAME: {{ .Values.global.secrets.azure.STORAGE_ACCOUNT_NAME }}
  AZURE_SERVICEBUS_CONNECTION_STR: {{ .Values.global.secrets.azure.AZURE_SERVICEBUS_CONNECTION_STR }}
  AZURE_SERVICEBUS_QUEUE_NAME: {{ .Values.global.secrets.azure.AZURE_SERVICEBUS_QUEUE_NAME }}
  {{- else }}
  CLOUD_NAME: UNKNOWN
  {{- end }}

---

{{- if .Values.global.secrets.aws.enable }}
{{- if not .Values.global.secrets.aws.use_iam_role }}
apiVersion: v1
data:
  key: {{ .Values.global.secrets.aws.AWS_ACCESS_KEY_ID | b64enc }}
  secret: {{ .Values.global.secrets.aws.AWS_SECRET_ACCESS_KEY | b64enc }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-secret
  namespace: {{ .Release.Namespace }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
{{- end }}
{{- end }}
