apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataset-raw-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "dataset-raw-controller.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "dataset-raw-controller.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | trim | nindent 8 }}
        {{- end }}
      labels:
        app.kubernetes.io/name: {{ include "dataset-raw-controller.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
        {{ .Values.global.snappyflowProjectLabel}}: {{ .Values.global.snappyflowProjectName }}
        {{ .Values.global.snappyflowAppLabel }}: {{ .Values.global.snappyflowAppName }}
    spec:
      {{- if .Values.global.sfScheduler.enabled }}
      schedulerName: {{ .Values.global.sfScheduler.schedulerName }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or (and .Values.global.secrets.aws.enable .Values.global.secrets.aws.use_iam_role) .Values.global.secrets.gcs.enable }}
      serviceAccountName: {{ .Release.Name }}-service-account
      {{- end}}
      initContainers:
        - name: db-ready
          image: "bitnami/postgresql:11.5.0-debian-9-r34"
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - "until pg_isready -d postgresql://'{{ .Values.global.postgresql.postgresqlUsername }}':'{{ .Values.global.postgresql.postgresqlPassword }}'@'{{ template "dataset-controller.postgresql.fullname" . }}':{{ .Values.global.postgresql.servicePort }}/'{{ .Values.global.postgresql.postgresqlDatabase }}'; do sleep 3; done"
{{- if .Values.global.secrets.minio.enable }}
        - name: kafka-ready
          image: "snappyflowml/kafka-zk-check:alpha"
          imagePullPolicy: IfNotPresent
          command:
            - /bin/bash
            - ./kafka-init.sh
            - {{ .Values.global.kafkaBrokers }}
{{- end }}
      containers:
        - name: dataset-raw-controller
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/conf
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-cloud-env
{{- if .Values.global.secrets.minio.enable }}
          env:
          - name: ORC_EVENT_CONTROLLER
            value: "{{ .Values.orcEventController.urlPath }}"
{{- end }}
{{- if not .Values.global.development }}
          resources: {{- toYaml .Values.containerResources | nindent 12 }}
{{- end }}
{{- if .Values.global.secrets.minio.enable }}
        - name: orc-event-controller
          image: "{{ .Values.orcEventController.image.repository }}:{{ .Values.orcEventController.image.tag }}"
          imagePullPolicy: {{ .Values.orcEventController.image.pullPolicy }}
          volumeMounts:
          - name: orc-event-controller-config-volume
            mountPath: /etc/conf
          resources: {{- toYaml .Values.orcEventController.containerResources | nindent 12 }}
{{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "dataset-raw-controller.fullname" . }}
{{- if .Values.global.secrets.minio.enable }}
        - name: orc-event-controller-config-volume
          configMap:
            name: {{ template "orc-event-controller.fullname" . }}
{{- end }}
