# Default values for sf-presto.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  sfScheduler: 
    enabled: false
    schedulerName: sf-scheduler
  snappyflowProjectLabel: snappyflow/projectname
  snappyflowAppLabel: snappyflow/appname

  snappyflowProjectName: "snappyflow-app"
  snappyflowAppName: "sf-presto"
    
replicaCount: 1

imagePullSecrets: []

image:
  repository: snappyflowml/presto
  pullPolicy: Always
  tag: latest

# Helm values for sfpresto-worker-prometheus-exporter container
sfprestoWorkerPrometheusExporter:
  image:
    repository: snappyflowml/sfpresto-worker-prometheus-exporter
    tag: latest
    pullPolicy: Always

  resources:
    requests:
      cpu: 100m
      memory: 200Mi

coordinator:
  resources:
    requests:
      cpu: 1000m
      memory: 8Gi
  # Provide Value same as Pod memory in Mi
  podmem: 8192

worker:
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: "1"
      memory: 4Gi
  # Provide Value same as Pod memory in Mi
  podmem: 4096

aws:
  enabled: false

azure:
  enabled: false

minio:
  enabled: false
  AWS_ACCESS_KEY_ID: XXXX
  AWS_SECRET_ACCESS_KEY: XXXX
  AWS_DEFAULT_REGION: default
  MINIO_ENDPOINT: XXXX

env:
  # Required onlu for azure
  STORAGE_ACCOUNT_NAME: ""
  # Required only for azure
  STORAGE_ACCOUNT_ACCESS_KEY: ""
  # How frequently sfpresto-worker-prometheus-exporter fetch metrics
  Metrics_Interval: 3
  # HiveMetaStore service
  HIVE_METASTORE_SERVICE: "archival-hive-metastore.kafka"
  # HiveMetaStore Service port
  HIVE_METASTORE_PORT: "9083"
  #Presto worker Graceful Shutdown Period
  Grace_Period_Seconds: 180

service:
  servicePort: 8080

podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: "2112"
  prometheus.io/scrape: "true"

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 5
  targetQueuedQueries: 5
  targetRunningDrivers: 50
  scaleUpPeriod: 30
  scaleDownPeriod: 60

terminationGracePeriodSeconds: 30

nodeSelector: {}
tolerations: []
affinity: {}
