---
enableDebug: false
archiverEnabled: true
nameOverride: sfapm-python3
fullnameOverride: ""
disable_server_side_cursors: false
podSecurityContext: {}
esmanager:
  image:
    repository: snappyflowml/sfapm-esmanager
    tag: '1-0-64'
    pullPolicy: IfNotPresent
