# Default values for redis.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  sfScheduler:
    enabled: false
    schedulerName: sf-scheduler
  sfappname: apm-server
  sfprojectname: apmdemo-sf-io
  sfappname_key: snappyflow/appname
  sfprojectname_key: snappyflow/projectname
  key: ""
    
replicaCount: 1

# if this is true, it will install redis 6.0 version for archival
archivalEnabled: false

image:
  repository: redis
  pullPolicy: IfNotPresent
  tag: "5.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 6379

persistence:
  enabled: true
  ## if enabled storage class name and size in GiB
  storageClass: ""
  size: 8Gi
  accessMode: ReadWriteOnce

config:
  redis.conf: |-
    appendonly yes

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
