---
enableDebug: false
nameOverride: sfapm-python3
fullnameOverride: ""
disable_server_side_cursors: false

vizbuilder:
  image:
    repository: snappyflowml/sfapm-vizbuilder
    tag: '4-0-231'
    pullPolicy: IfNotPresent

vizbuilder_celery:
  alert:
    celeryAlertPrometheusExporter:
      image:
        repository: snappyflowml/celery-alert-prometheus-exporter
        tag: '4-0-231'
        pullPolicy: Always
